# Generated by Django 4.1.7 on 2023-02-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='date',
        ),
        migrations.AddField(
            model_name='tasks',
            name='deadline',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
