# Generated by Django 4.1.7 on 2023-02-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tasks_is_complete_alter_tasks_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='user',
            field=models.CharField(default='', max_length=30, verbose_name='Пользователь'),
        ),
    ]
